# Generated by Django 2.1.2 on 2018-11-16 00:52

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import taobao.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('commodity_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('commodity_name', models.CharField(max_length=200)),
                ('commodity_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('commodity_sort', models.CharField(max_length=200)),
                ('stock', models.IntegerField(default=0)),
                ('commodity_photo', models.FileField(upload_to=taobao.models.commodity_upload_to)),
                ('publish_date', models.DateTimeField(default=datetime.datetime(2018, 11, 16, 0, 52, 43, 671283, tzinfo=utc))),
                ('modify_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Commodity',
            },
        ),
        migrations.CreateModel(
            name='Commodity_sort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_name', models.CharField(max_length=200)),
                ('sort_shortcut', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'commodity_sort',
            },
        ),
        migrations.CreateModel(
            name='Shopping_cart',
            fields=[
                ('commodity_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('commodity_name', models.CharField(max_length=200)),
                ('commodity_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('commodity_num', models.IntegerField()),
                ('commodity_sum', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'Shopping_cart',
            },
        ),
        migrations.CreateModel(
            name='User_login_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'user_login_history',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_account', models.CharField(max_length=20)),
                ('user_password', models.CharField(max_length=200)),
                ('user_question', models.CharField(default='', max_length=50)),
                ('user_answer', models.CharField(default='', max_length=50)),
                ('user_name', models.CharField(default='', max_length=20)),
                ('user_RMB', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('user_time', models.DateTimeField(auto_now_add=True)),
                ('user_state', models.CharField(default='0', max_length=20)),
                ('user_portrait', models.FileField(default='portrait/default.jpg', upload_to=taobao.models.user_upload_to)),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.AddField(
            model_name='user_login_history',
            name='loginuser_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taobao.Users'),
        ),
        migrations.AddField(
            model_name='shopping_cart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taobao.Users'),
        ),
        migrations.AddField(
            model_name='commodity',
            name='commodity_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taobao.Users'),
        ),
    ]
